# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-15 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('contribution1', otree.db.models.PositiveIntegerField(null=True, verbose_name='contribution')),
                ('contribution2', otree.db.models.PositiveIntegerField(null=True, verbose_name='contribution')),
                ('contribution3', otree.db.models.PositiveIntegerField(null=True, verbose_name='contribution')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson2_group', to='otree.Session')),
            ],
            options={
                'db_table': 'lesson2_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('maximum_contribution', otree.db.models.PositiveIntegerField(null=True, verbose_name='What is the maximum contribution that a player can make?')),
                ('minimum_contribution', otree.db.models.PositiveIntegerField(null=True, verbose_name='What is the minimum contribution that a player can make?')),
                ('multiplier', otree.db.models.PositiveIntegerField(null=True, verbose_name='What is the size of the multiplier?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson2.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson2_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson2_player', to='otree.Session')),
            ],
            options={
                'db_table': 'lesson2_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson2_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'lesson2_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson2.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson2.Subsession'),
        ),
    ]
