# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-30 10:21
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0002_remove_subsession_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='trust',
            field=otree.db.models.PositiveIntegerField(null=True),
        ),
    ]
