# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-29 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins
import radiogrid.db


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('name', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What is your name?')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_group', to='otree.Session')),
            ],
            options={
                'db_table': 'feedback_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('syntax', otree.db.models.IntegerField(choices=[[1, 'Unsure'], [2, 'Agree partially'], [3, 'Agree']], null=True, verbose_name='I know how to search advice online')),
                ('structure', otree.db.models.IntegerField(choices=[[1, 'Unsure'], [2, 'Agree partially'], [3, 'Agree']], null=True, verbose_name='I feel confident to start coding my oTree projects - I know at least where to start - ')),
                ('debugging', otree.db.models.IntegerField(choices=[[1, 'Unsure'], [2, 'Agree partially'], [3, 'Agree']], null=True, verbose_name='I can decode error messages and find potential out which file is the source of the error')),
                ('breakdown', otree.db.models.IntegerField(choices=[[1, 'Unsure'], [2, 'Agree partially'], [3, 'Agree']], null=True, verbose_name='I can break down a coding project into smaller problems')),
                ('sentences', otree.db.models.IntegerField(choices=[[1, 'Unsure'], [2, 'Agree partially'], [3, 'Agree']], null=True, verbose_name='I can figure out how to do if and for sentences in python, Django, and JavaScript')),
                ('difficulty', otree.db.models.IntegerField(choices=[[1, 'Too easy'], [2, 'Ok'], [3, 'Too difficult']], null=True, verbose_name='I found the course')),
                ('good', otree.db.models.LongStringField(blank=True, null=True, verbose_name='Can you remember any good coding practise advice? Please, mention some below:')),
                ('useful', otree.db.models.LongStringField(blank=True, null=True, verbose_name='I found most useful in the course?')),
                ('future', otree.db.models.BooleanField(choices=[[1, 'Yes'], [2, 'No']], verbose_name='I think I will be using oTree in the future')),
                ('missing', otree.db.models.LongStringField(blank=True, null=True, verbose_name='I wish the course would have also covered the following:')),
                ('comment', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='You can leave a free comment here:')),
                ('name', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What is your name?')),
                ('age', otree.db.models.PositiveIntegerField(null=True, verbose_name='What is your age?')),
                ('occupation', otree.db.models.StringField(max_length=10000, null=True)),
                ('student', otree.db.models.BooleanField(choices=[[1, 'yes'], [2, 'no']])),
                ('department', otree.db.models.StringField(choices=[['Eco', 'Economics'], ['SPS', 'Social and Political Sciences']], max_length=10000, null=True)),
                ('expectations', otree.db.models.CurrencyField(null=True, verbose_name='How many points do you expect to earn?')),
                ('pi', otree.db.models.FloatField(null=True, verbose_name='How many digits of the mathematical constant Pi do you recall?')),
                ('agree', radiogrid.db.RadioGridField(null=True, require_all_fields=True, rows=((1, 'I like blue'), (2, 'I like red')), values=((1, 'Agreed'), (2, 'Disagreed')), verbose_name='Do you agree?')),
                ('sunny', otree.db.models.IntegerField(choices=[[1, 'agree'], [2, 'agree somewhat'], [3, "don't know"], [4, 'disagree somewhat'], [5, 'disagree']], null=True, verbose_name='It is sunny outside')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_player', to='otree.Session')),
            ],
            options={
                'db_table': 'feedback_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'feedback_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Subsession'),
        ),
    ]
